services:
  - type: web
    name: eliza-os-agent
    env: node
    plan: standard
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add other required environment variables here
